### ISSUE TITLE
Release 1.5.0 Update

### ISSUE THREAD

**Issue by sanduhrs** [Mailu/Rancher#8]
With the latest release of Mailu this probably needs an update too?
https://github.com/Mailu/Mailu/releases/tag/v1.5.0

**Comment by kaiyou** [comment]
Yes, it does. Also, it would be very nice if we could integrate all of this in ``docs/rancher`` and directly into https://mailu.io :)

**Comment by sanduhrs** [comment]
I updated at #10

**Comment by kaiyou** [comment]
Just merged, thanks!
