### ISSUE TITLE
can anyone make heads or tails of this ??

### ISSUE THREAD

**Issue by ghost** [Mailu/Rancher#9]
im trying to deploy from the catalog with a self signed cert in /mailu/certs and listen on 0.0.0.0 yet http sees to fail loading with this error

and the admin container fails with 
Failed to allocate instance [container:1i98]: Bad instance [container:1i98] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [127.0.0.1:8000:80/tcp portReservation, instanceReservation: 1].

why is it even trying 127.0.0.1 ??

1/25/2018 6:36:26 PMwriting new private key to '/tmp/snakeoil.pem'
1/25/2018 6:36:26 PM-----
1/25/2018 6:36:26 PM2018/01/25 23:36:26 [emerg] 14#14: host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:36:26 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:36:39 PMGenerating a 2048 bit RSA private key
1/25/2018 6:36:39 PM....................................................+++
1/25/2018 6:36:39 PM.......................+++
1/25/2018 6:36:39 PMwriting new private key to '/tmp/snakeoil.pem'
1/25/2018 6:36:39 PM-----
1/25/2018 6:36:39 PM2018/01/25 23:36:39 [emerg] 13#13: host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:36:39 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:36:54 PMGenerating a 2048 bit RSA private key
1/25/2018 6:36:54 PM................................................................................................+++
1/25/2018 6:36:54 PM.+++
1/25/2018 6:36:54 PMwriting new private key to '/tmp/snakeoil.pem'
1/25/2018 6:36:54 PM-----
1/25/2018 6:36:54 PM2018/01/25 23:36:54 [emerg] 13#13: host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:36:54 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:37:09 PMGenerating a 2048 bit RSA private key
1/25/2018 6:37:09 PM....................................................+++
1/25/2018 6:37:09 PM...........................+++
1/25/2018 6:37:09 PMwriting new private key to '/tmp/snakeoil.pem'
1/25/2018 6:37:09 PM-----
1/25/2018 6:37:09 PM2018/01/25 23:37:09 [emerg] 13#13: host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:37:09 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:37:10 PMGenerating a 2048 bit RSA private key
1/25/2018 6:37:10 PM.............+++
1/25/2018 6:37:10 PM.......................................................+++
1/25/2018 6:37:10 PMwriting new private key to '/tmp/snakeoil.pem'
1/25/2018 6:37:10 PM-----
1/25/2018 6:37:10 PM2018/01/25 23:37:10 [emerg] 13#13: host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:37:10 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:43
1/25/2018 6:37:24 PM2018/01/25 23:37:24 [emerg] 12#12: host not found in upstream "admin" in /etc/nginx/nginx.conf:76
1/25/2018 6:37:24 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:76
1/25/2018 6:37:25 PM2018/01/25 23:37:25 [emerg] 12#12: host not found in upstream "admin" in /etc/nginx/nginx.conf:76
1/25/2018 6:37:25 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:76
1/25/2018 6:37:39 PM2018/01/25 23:37:39 [emerg] 12#12: host not found in upstream "admin" in /etc/nginx/nginx.conf:76
1/25/2018 6:37:39 PMnginx: [emerg] host not found in upstream "admin" in /etc/nginx/nginx.conf:76

**Comment by kaiyou** [comment]
Do you have a proper documentation on setting up Rancher? I suggest we debug this together, update this repo which is way out of date (the rancher file probably just doesn't work) and move all of the stuff to the main repo.
